CONFIG_BOOT_BANNER=y

CONFIG_NET_BUF=y

CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_PRODUCT="Zephyr USB console sample"
CONFIG_USB_DEVICE_PID=0x0004
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=n
CONFIG_USB_DEVICE_AUDIO=y
CONFIG_USBD_AUDIO2_CLASS=y

CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_LINE_CTRL=y

CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y

CONFIG_PRINTK=y
CONFIG_GPIO=y

CONFIG_I2C=y
CONFIG_I2S=y
CONFIG_AUDIO=y
CONFIG_AUDIO_CODEC=y
CONFIG_AUDIO_CODEC_CS43L22=y
CONFIG_AUDIO_CODEC_SHELL=y

CONFIG_LOG=y
CONFIG_USB_DRIVER_LOG_LEVEL_ERR=y
CONFIG_USB_DEVICE_LOG_LEVEL_ERR=y

#CONFIG_NEWLIB_LIBC=n
#CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=n

CONFIG_REQUIRES_FULL_LIBC=y
CONFIG_REQUIRES_FLOAT_PRINTF=y

CONFIG_CMSIS_DSP=y
CONFIG_CMSIS_DSP_COMPLEXMATH=n
CONFIG_CMSIS_DSP_TRANSFORM=n
CONFIG_CMSIS_DSP_FASTMATH=n
CONFIG_CMSIS_DSP_CONTROLLER=y

CONFIG_DEBUG=y
CONFIG_I2S_LOG_LEVEL_DBG=y
#CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_LOG_RUNTIME_FILTERING=y
CONFIG_LOG_CMDS=y
