
CONFIG_COUNTER=y
#CONFIG_TIMER=y
#CONFIG_COUNTER_STM32_TIMER=y
#CONFIG_USE_STM32_HAL_TIM=y
CONFIG_COUNTER_TIMER_STM32=y
CONFIG_GPIO_STM32=y
#CONFIG_USE_STM32_HAL=y
#CONFIG_USE_STM32_HAL_GPIO=y

#CONFIG_USE_STM32_HAL_TIM=y
#CONFIG_USE_STM32_HAL_TIM_EX=y
